{{- $endpoint := .Values.backend -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/issuer: {{ .Release.Name }}
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/oauth2/userinfo(.*)$ /userinfo$1 break;
spec:
  tls:
    - hosts:
        - {{printf "%s%s" .Values.ingress.hostnamePrefix .Values.ingress.hostname }}
      secretName: {{ .Release.Name}}-ssl-secret
  rules:
    - host: {{printf "%s%s" .Values.ingress.hostnamePrefix .Values.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ $endpoint.service.name }}
              servicePort: {{ $endpoint.service.port }}
